### ISSUE TITLE
release 1.0.0 for w32 is not working

### ISSUE THREAD

**Issue by kimtang** [KxSystems/embedR#6]
release 1.0.0 for w32 is not working

**Comment by cmccarthy1** [comment]
Hi @kimtang,

I was able to get the w32 build for 1.0.0 working recently using the install instructions provided in the README.md, could you please provide some more information on the issue you are seeing such that I can replicate your issue.

All the best,

Conor

**Comment by cmccarthy1** [comment]
@kimtang I'm closing this issue for now, if you can provide information on an instruction set that will allow me to replicate this please feel free to reopen the issue.
